############### Defaults ###############
########################################
PARAMS: &defaults

  # PROCESSING PARAMETERS
  DURATION      : 600   # DON'T CHANGE THIS!
  LATENCY       : 30     # how long to pause and wait for data latency to catch up before processing (seconds)
  EXTRA_PAUSE   : 0     # extra pause in case some arrays are extra latent (Dillingham)
  FREQMIN       : 1.0   # minimum frequency
  FREQMAX       : 10.0   # maximum frequency
  TAPER         : 5.0   # seconds to taper beginning and end of trace before filtering
  WINDOW_LENGTH : 30    # window length for each calculation [seconds]
  OVERLAP       : 15    # amount of overlap between windows [seconds]
  MIN_CHAN      : 3     # minimum number of channels needed to perform inversion
  LTS_ALPHA     : 0.5   # decimal [0.50, 1.0] amount of data to keep in the subsets

  # PLOTTING PARAMETERS
  PLOT_MCCM     : True  # make MdCCM scatter subplot
  MCTHRESH      : 0.6   # where to draw the threshold line in MCCM plot
  AZ_MIN        : 0     # minimum azimuth to plot
  AZ_MAX        : 360   # maximum azimuth to plot
  VEL_MIN       : 0.25  # minimum sound speed range
  VEL_MAX       : 0.45  # maximum sound speed range
  ARRAY_LABEL   : Infrasound
########################################
########################################


# Define arrays to be processed
NETWORKS:
  HVO:
    - UWE
    - AHUD
    - MENE
    - AIND
    - SHEEP
    - Kahaluu


# Configure each array's channels, back-azimuth targets, 
# and (optionally) different pre-processing/plotting parameters
UWE:
  <<: *defaults
  NSLC: 
    - HV.UWE.01.HDF
    - HV.UWE.02.HDF
    - HV.UWE.03.HDF
    - HV.UWE.04.HDF
    - HV.UWE.05.HDF
    - HV.UWE.06.HDF
  TARGETS: 
    - Kulani
    - North Vent
    - Puu Oo
    - ML summit
    - PLAD
    - MLOD
    - Kapoho Crater
    - KOSM
    - SHEEP
  # AZ_MIN: 0
  # AZ_MAX: 360

AHUD:
  <<: *defaults
  NSLC: 
    - HV.AHUD.01.HDF
    - HV.AHUD.02.HDF
    - HV.AHUD.03.HDF
    - HV.AHUD.04.HDF
    - HV.AHUD.05.HDF
    - HV.AHUD.06.HDF
  TARGETS: 
    - North Vent
    - Puu Oo
    - ML summit
    - KOSM
    - RCOD
    - PLAD
    - MLOD
    - DAND
    - HOVE
  # AZ_MIN: 0
  # AZ_MAX: 360

MENE:
  <<: *defaults
  NSLC: 
    - HV.MENE.01.HDF
    - HV.MENE.02.HDF
    - HV.MENE.03.HDF
    - HV.MENE.04.HDF
  TARGETS: 
    - Kulani
    - ML summit
    - HOVE
    - MLOD
    - North Vent
    - Mauna Ulu
    - Puu Oo
    - Napau Crater
    - KOSM
  # AZ_MIN: 60
  # AZ_MAX: 270

AIND:
  <<: *defaults
  NSLC: 
    - HV.AIND.01.HDF
    - HV.AIND.02.HDF
    - HV.AIND.03.HDF
    - HV.AIND.04.HDF
  TARGETS: 
    - North Vent
    - Puu Oo
    - KOSM
    - ML summit
    - Pahala
    - RCOD
    - PLAD
    - MLOD
    - DAND
    - HOVE
  # AZ_MIN: 205
  # AZ_MAX: 30

SHEEP:
  <<: *defaults
  NSLC: 
    - HV.SHEEP.01.HDF
    - HV.SHEEP.02.HDF
    - HV.SHEEP.03.HDF
    - HV.SHEEP.04.HDF
    - HV.SHEEP.05.HDF
    - HV.SHEEP.06.HDF
  TARGETS: 
    - Kulani
    - Halemaumau
    - Puu Oo
    - ML summit
    - PLAD
    - MLOD
    - Kapoho Crater
  # AZ_MIN: 100
  # AZ_MAX: 270

Kahaluu:
  <<: *defaults
  NSLC:
    - IM.I59H1.--.BDF
    - IM.I59H2.--.BDF
    - IM.I59H3.--.BDF
    - IM.I59H4.--.BDF
  TARGETS:
    - Hualalai
    - Maunakea
    - ML summit
    - RCOD
    - PLAD
    - MLOD
    - DAND
    - HOVE
  # AZ_MIN : 0
  # AZ_MAX : 240
  EXTRA_PAUSE: 210

##                               ##
# Example of manual metadata entry:
##                               ##
# Wake Island South:
#   <<: *hydro_defaults
#   NSLC:
#     IM.H11S1..BDF:
#       lat: 18.50827
#       lon: 166.700272
#       gain: 1860.86
#     IM.H11S2..BDF:
#       lat: 18.49082
#       lon: 166.705002
#       gain: 1860.86
#     IM.H11S3..BDF:
#       lat: 18.49568    # put station latitude in directly
#       lon: 166.686462  # put station longitude in directly
#       gain: 1860.86    # put station gain in directly
#   TARGETS:
#     Saipan: 263.8      # put target back-azimuth in directly
#     Anatahan: 267.1
#     Ahyi: 278.0


## optional urls that get linked from the iPensive webpage
EXTRA_LINKS:
  - Data Output: ../tests/ascii_output/
  - Array Locations: https://ds.iris.edu/gmap/#network=HV,IM&channel=*DF&maxlat=21&maxlon=-154&minlat=18&minlon=-157&drawingmode=box&planet=earth
  