############### Defaults ###############
########################################
PARAMS: &defaults # define reusable key-value pairs

  # PROCESSING PARAMETERS
  EXTRA_PAUSE   : 0     # extra pause in case some arrays are extra latent (Dillingham)
  FREQMIN       : 0.8   # minimum frequency
  FREQMAX       : 5.0   # maximum frequency
  TAPER         : 5.0   # seconds to taper beginning and end of trace before filtering
  WINDOW_LENGTH : 30    # window length for each calculation [seconds]
  OVERLAP       : 15    # amount of overlap between windows [seconds]
  MIN_CHAN      : 3     # minimum number of channels needed to perform inversion
  LTS_ALPHA     : 0.75  # decimal [0.50, 1.0] amount of data to keep in the subsets

  # PLOTTING PARAMETERS
  PLOT_MCCM     : True  # make MdCCM scatter subplot
  MCTHRESH      : 0.6   # where to draw the threshold line in MCCM plot
  AZ_MIN        : 0     # minimum azimuth to plot
  AZ_MAX        : 360   # maximum azimuth to plot
  VEL_MIN       : 0.25  # minimum sound speed range
  VEL_MAX       : 0.45  # maximum sound speed range
  ARRAY_LABEL   : Infrasound
########################################
########################################


# Define arrays to be processed
NETWORKS:
  AVO:
    - Kenai
    - Sand Point
  CNMI:
    - Saipan
    - Wake Island North
    - Wake Island South


# Configure each array's channels, back-azimuth targets, 
# and (optionally) different pre-processing/plotting parameters
Kenai:
  <<: *defaults # reusable defaults from PARAMS above
  NSLC: 
    - AV.KENI.01.HDF
    - AV.KENI.02.HDF
    - AV.KENI.03.HDF
    - AV.KENI.04.HDF
    - AV.KENI.05.HDF
    - AV.KENI.06.HDF
  TARGETS: 
    - Wrangell
    - Spurr
    - Redoubt
    - Iliamna
    - Augustine
  AZ_MIN: 200
  AZ_MAX: 80
  # PLOTCHAN:  # optional specify a single channel to plot waveforms from 
  #              (defaults to first in obspy stream). Also controls peak
  #              pressure calculations.

Sand Point:
  <<: *defaults
  NSLC: 
    - AV.SDPI.01.HDF
    - AV.SDPI.02.HDF
    - AV.SDPI.03.HDF
    - AV.SDPI.04.HDF
    - AV.SDPI.05.HDF
    - AV.SDPI.06.HDF
  TARGETS: 
    - Pavlof
    - Veniaminof
    - Shishaldin
    - Trident
  AZ_MIN: 240
  AZ_MAX: 60
  FREQMIN: 1

Saipan:
  <<: *defaults
  NSLC:
    - MI.FLX.01.HDF
    - MI.FLX.02.HDF
    - MI.FLX.03.HDF
    - MI.FLX.04.HDF
    - MI.FLX.05.HDF
    - MI.FLX.06.HDF
  TARGETS:
    - Anatahan
    - Pagan
  AZ_MIN: 205
  AZ_MAX: 15

Wake Island North: &hydro_defaults
  <<: *defaults
  NSLC:
    - IM.H11N1.--.EDH
    - IM.H11N2.--.EDH
    - IM.H11N3.--.EDH
  TARGETS:
    - Saipan
    - Anatahan
    - Pagan
    - Ahyi Seamount
  FREQMIN: 1
  FREQMAX: 10
  VEL_MIN: 1.4
  VEL_MAX: 1.6
  AZ_MIN : 250
  AZ_MAX : 290
  ARRAY_LABEL: Hydroacoustic

##                               ##
# Example of manual metadata entry:
##                               ##
Wake Island South:
  <<: *hydro_defaults
  NSLC:
    IM.H11S1..EDH:
      lat: 18.50827
      lon: 166.700272
      gain: 1860.86
    IM.H11S2..EDH:
      lat: 18.49082
      lon: 166.705002
      gain: 1860.86
    IM.H11S3..EDH:
      lat: 18.49568    # put station latitude in directly
      lon: 166.686462  # put station longitude in directly
      gain: 1860.86    # put station gain in directly
  TARGETS:
    Saipan: 263.8      # put target back-azimuth in directly
    Anatahan: 267.1
    Ahyi: 278.0